version: '2'

services:
  myapp:
    image: docker.io/bitnami/codeigniter:4
    ports:
      - '8000:8000'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '../project-root:/app'